display_name: Slive
package_name: Slive
maintainer:
  name: slotsun
  email: slot_sun@outlook.com
priority: optional
section: x11
installed_size: 24400
essential: false
icon: assets/images/logo.png

generic_name: Livestream Player

keywords:
  - Livestream
  - Video

categories:
  - AudioVideo
  - Audio
  - Video
  - Network

startup_notify: true

dependencies:
  - libmpv2

metainfo: assets/io.github.SlotSun.dart_simple_live.metainfo.xml
